# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
#
# .travis.ytml file examples:
#
#  * https://github.com/cdeterman/gpuR/blob/develop/.travis.yml

# whitelist branches
branches:
  only:
    - master

language: r
sudo: false
warnings_are_errors: false
cache: packages

r:
  # - oldrel
  - release
  # - devel

# R packages
r_packages:
 - httpcode
 - httr
 - MazamaCoreUtils
